env:
        browser: true
        es2021: true
extends:
        - eslint:recommended
        - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
        ecmaVersion: latest
        sourceType: module
plugins:
        - '@typescript-eslint'
rules:
        indent:
                - error
                - 2
                - SwitchCase: 1
        max-len:
                - error
                - 250
        no-irregular-whitespace: 2
        no-multi-spaces: 2
        no-undefined: 2
        no-param-reassign: 2
        linebreak-style:
                - error
                - unix
        quotes:
                - error
                - single
        object-curly-spacing: ["warn", "always"]
